### ISSUE TITLE
Sidebar Not Loading Consistently

### ISSUE THREAD

**Issue by 400HPMustang** [DBuit/sidebar-card#33] opened 2021-05-13 17:13 UTC
I just installed this yesterday and the issue I'm having is that sidebar doesn't consistently load. I can reload the the page a few times and the sidebar will show. When I try to navigate to one of the other paths in the dashboard (lights, security, etc) from the sidebar I get bounced back to my default dashboard which is just the default lovelace view. The header bar does however work correctly.

```
sidebarMenu:
    - action: navigate
      navigation_path: /lovelace-tablet/main
      name: Home
      active: true
    - action: navigate
      navigation_path: /lovelace-tabet/lights
      name: Lights
    - action: navigate
      navigation_path: /lovelace-tablet/security
      name: Security
    - action: navigate
      navigation_path: /lovelace-tablet/media
      name: Media
```

**Comment by doosterkamp** [comment] 2021-05-18 14:18
Please look at other issues before creating new ones!
This is a duplicate of #14 and #20

I already created a fix for it and we're waiting for @DBuit to merge my pull request

**Comment by wtrbuit** [comment] 2021-08-31 10:42
Hi @400HPMustang, we have accepted @doosterkamp PR and released a new version. Can you check if the issue still occurs?

**Closed** 2021-08-31 10:43 UTC
