### ISSUE TITLE
hideTopMenu doesn't hide top menu

### ISSUE THREAD

**Issue by 400HPMustang** [DBuit/sidebar-card#34] opened 2021-05-13 21:55 UTC
![Screen Shot 2021-05-13 at 4 54 48 PM](https://user-images.githubusercontent.com/45641587/118192654-13385c00-b40c-11eb-816f-42fc578156dc.png)

sidebar config

```
sidebar:
  digitalClock: true
  twelveHourVersion: true
  date: true
  width:
    mobile: 0
    tablet: 20
    desktop: 20
  hideTopMenu: true
  hideHassSidebar: true
  breakpoints:
    mobile: 768
    tablet: 1024
  sidebarMenu:
    - action: navigate
      navigation_path: /lovelace-tablet/main
      name: Home
      active: true
    - action: navigate
      navigation_path: /lovelace-tabet/lights
      name: Lights
    - action: navigate
      navigation_path: /lovelace-tablet/security
      name: Security
    - action: navigate
      navigation_path: /lovelace-tablet/media
      name: Media
```

**Comment by doosterkamp** [comment] 2021-05-18 14:16
Please look at other issues before creating new ones!
This is a duplicate of #21 

I already created a fix for it and we're waiting for @DBuit to merge my pull request

**Closed** 2021-08-31 10:43 UTC
